FROM node:23-alpine as node
FROM ruby:3.4.4-alpine3.21

ARG NODE_VERSION="23.7.0"
ARG PNPM_VERSION="10.2.0"
ENV NODE_VERSION=${NODE_VERSION}
ENV PNPM_VERSION=${PNPM_VERSION}

ARG BUNDLE_WITHOUT=""
ENV BUNDLE_WITHOUT ${BUNDLE_WITHOUT}
ENV BUNDLER_VERSION=2.5.11

ARG RAILS_SERVE_STATIC_FILES=false
ENV RAILS_SERVE_STATIC_FILES ${RAILS_SERVE_STATIC_FILES}

ARG RAILS_ENV=development
ENV RAILS_ENV ${RAILS_ENV}

ARG NODE_OPTIONS="--max-old-space-size=4096"
ENV NODE_OPTIONS ${NODE_OPTIONS}

ENV BUNDLE_PATH="/usr/local/bundle"

# Install system dependencies
RUN apk update && apk add --no-cache \
  openssl \
  tar \
  build-base \
  tzdata \
  postgresql-dev \
  postgresql-client \
  git \
  curl \
  xz \
  musl \
  ruby-dev \
  gcc \
  make \
  musl-dev \
  openssl-dev \
  g++ \
  linux-headers \
  vips \
  imagemagick \
  bash \
  vim \
  && rm -rf /var/cache/apk/* \
  && gem install bundler

# Copy Node from official image
COPY --from=node /usr/local/bin/node /usr/local/bin/
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
  && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

# Install pnpm
RUN npm install -g pnpm@${PNPM_VERSION}

# Setup pnpm environment
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

# Install gems (will be cached if Gemfile doesn't change)
COPY Gemfile Gemfile.lock ./
RUN bundle config set --local force_ruby_platform true
RUN bundle install -j 4

# Install node packages (will be cached if package.json doesn't change)
COPY package.json pnpm-lock.yaml ./
RUN pnpm i

# Copy application code (in dev mode, this will be mounted as volume)
COPY . /app

# Create necessary directories
RUN mkdir -p /app/log /app/tmp /app/storage

EXPOSE 3000
EXPOSE 3036

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
