services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: ''
        EXECJS_RUNTIME: 'Node'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    tty: true
    stdin_open: true
    image: chatwoot:development
    env_file: .env

  rails:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/rails.Dockerfile
    image: chatwoot-rails:development
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - redis
      - mailhog
      - sidekiq
    ports:
      - 0.0.0.0:3000:3000
    env_file: .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - NODE_ENV=production
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - OPENAI_API_KEY=ollama
      - OPENAI_API_BASE=http://ollama:11434
      - OPENAI_GPT_MODEL=qwen2.5:3b
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    image: chatwoot-rails:development
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - redis
      - mailhog
    env_file: .env
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - OPENAI_API_KEY=ollama
      - OPENAI_API_BASE=http://ollama:11434
      - OPENAI_GPT_MODEL=qwen2.5:3b
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  # vite:
  #   <<: *base
  #   build:
  #     context: .
  #     dockerfile: ./docker/dockerfiles/vite.Dockerfile
  #   image: chatwoot-vite:development
  #   volumes:
  #     - ./:/app:delegated
  #     - node_modules:/app/node_modules
  #     - packs:/app/public/packs
  #     - cache:/app/tmp/cache
  #     - bundle:/usr/local/bundle
  #   ports:
  #     - "0.0.0.0:3036:3036" # Vite dev server
  #   environment:
  #     - VITE_DEV_SERVER_HOST=0.0.0.0
  #     - NODE_ENV=production
  #     - RAILS_ENV=production
  #   entrypoint: docker/entrypoints/vite.sh
  #   command: bin/vite dev

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot_password

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis:/data/redis
    ports:
      - '0.0.0.0:6379:6379'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 0.0.0.0:1025:1025
      - 0.0.0.0:8025:8025

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - chatwoot_ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

volumes:
  postgres:
  redis:
  chatwoot_ollama_data:
    external: true